### ISSUE TITLE
Error While Restart Node: "p2p_client-cli: to few bytes"

### ISSUE THREAD

**Issue by ilhamm24** [Concordium/Testnet3-Challenges#1109]
I got this error while restarting my nodes
`2020-10-28T09:41:35.785747599Z: INFO: Starting up the consensus layer
p2p_client-cli: too few bytes
From:   Accounts
        demandInput

 :: ""
CallStack (from HasCallStack):
  error, called at src/Concordium/GlobalState/Persistent/BlobStore.hs:268:19 in globalstate-0.1.0.0-inplace:Concordium.GlobalState.Persistent.BlobStore
  loadRef, called at src/Concordium/GlobalState/Persistent/BlobStore.hs:769:30 in globalstate-0.1.0.0-inplace:Concordium.GlobalState.Persistent.BlobStore
XU: warning: too many hs_exit()s`

**Comment by ab-concordium** [comment]
Unfortunately that indicates that the node's database is corrupt. This most often happens when the node does not shutdown properly, e.g., it is killed, or runs out of resources. The solution is to run `reset-data` and restart the node.

Before you do that, can you send us the node database and the logs at the end of your previous run so we can investigate what caused the issue?

If you are running this on linux then the node database is stored in `~/.local/share/concordium/database-v3`.

**Comment by ilhamm24** [comment]
Sorry i cant. Because i already flush while start node again, also for node log, i think my node dont have realtime log save

**Comment by ilhamm24** [comment]
But, i turned off propely. I always turned off node with ctrl+c and `concordium-node-stop`

**Comment by ilhamm24** [comment]
so, later I will continue this issue when I experience this again
