### ISSUE TITLE
missing log output

### ISSUE THREAD

**Issue by myasin59** [Concordium/Testnet3-Challenges#1161]
I'm trying to log with the new script. My node, which I run for 7 days for the b2 task, generates 1 daily logs. What is the reason?
b2 taskfor this node is turned on and off twice a day)

**Comment by supermario** [comment]
I’m confused about what the issue is. The log summary tool will summarize your entire log, so you should get one summary file, and optionally another file describing your system. 

What is the problem you’re having?

**Comment by myasin59** [comment]
as I mentioned above, I installed a new node for the b2 task and ran it for 7 days. Now I'm trying to get a log and it only produces me a 1-day log

**Comment by supermario** [comment]
@myasin59 can you please attach the summary log you are getting from the [`retrieve_minified_logs`](https://github.com/Concordium/Testnet3-Challenges/blob/main/logs.md) tool?

**Comment by myasin59** [comment]
[concordium-testnet-node-b2b3dbebf175aec28534841f0b68438f88e7ab382a3f0ac6d4c2a28151b8379f.log](https://github.com/Concordium/Testnet3-Challenges/files/5458747/concordium-testnet-node-b2b3dbebf175aec28534841f0b68438f88e7ab382a3f0ac6d4c2a28151b8379f.log)

**Comment by supermario** [comment]
@myasin59 so according to the logs you're submitting, this node was started for the first time at `2020-10-25T14:59` and run for approx 33 hours. 

If you've run this node for 7 days and this is the log that's being produced, then it would seem you cleared/reset your data at some point, or those logs were removed/cycled for some reason, because those logs are not present on your system according to this summary.

One way to check would be to look at the [Log sizes & rotation](https://github.com/Concordium/Testnet3-Challenges/blob/main/logs.md#log-sizes--rotation) section and use that to see your logs location and the size/contents of those logs to see what might be going on.

**Comment by concordium-admin** [comment]
No further analysis possible without details on logs.
