### ISSUE TITLE
 Add someone else's accounts  and learning their identity

### ISSUE THREAD

**Issue by donadel01** [Concordium/Testnet3-Challenges#1619]
Code 1 - ./concordium-client config account add 3o1JLuuLbko3VkkpwFJVvfMgwygQ5SX3t5feYXFLqdDmnLSNns --name hdrns01

Result : 
Adding account 3o1JLuuLbko3VkkpwFJVvfMgwygQ5SX3t5feYXFLqdDmnLSNns with name 'hdrns01'.
Creating directory '/var/lib/concordium/config/accounts/3o1JLuuLbko3VkkpwFJVvfMgwygQ5SX3t5feYXFLqdDmnLSNns'.
Created key directory.
Writing file '/var/lib/concordium/config/accounts/names.map'.
Added name mapping.

Code2- ./concordium-client config show

Result : Base configuration:
- Verbose:            no
- Account config dir: /var/lib/concordium/config/accounts
- Account name map:
    Dona -> 3UYPS3Zbm8bTBXLcob7f9Y8TjamndqqMjbCRs45hSFpBJUX3oA
    T1 -> 4XgbW1qRxFiUtcZW2B9G8q9k2ThJpn5yn1ibrEjC5qbyDhEmVf
    T2 -> 3AXrqVzeFibTJsKGFTonjCjTrM7Vv342W498REQ59L563afZc8
    hdrns01 -> 3o1JLuuLbko3VkkpwFJVvfMgwygQ5SX3t5feYXFLqdDmnLSNns

concordium-client: /var/lib/concordium/config/accounts/3o1JLuuLbko3VkkpwFJVvfMgwygQ5SX3t5feYXFLqdDmnLSNns/encSecretKey.json: openBinaryFile: does not exist (No such file or directory)

As a result, I added someone else's account to my own node. If I tried a little more, I could transfer money from this account. Someone more professional could benefit from this.

**Comment by donadel01** [comment]
code : $ ./concordium-client account show hdrns01

Result:
Local name:            hdrns01
Address:               3o1JLuuLbko3VkkpwFJVvfMgwygQ5SX3t5feYXFLqdDmnLSNns
Balance:               775.963200 GTU
Nonce:                 1254
Delegation:            none
Encryption public key: a820662531d0aac70b3a80dd8a249aa692436097d06da005aec7c56aad17997ec8331d1e4050fd8dced2b92f06277bd581285b692c4d15ec49d1214c89021ae31a287f529dcb41829a12079dc982d2c60e720b897a5580fa078a6675e67943e3


Credentials:
* 81285b692c4d15ec49d1214c89021ae31a287f529dcb41829a12079dc982d2c60e720b897a5580fa078a6675e67943e3:
  - Expiration: Sep 2021
  - Revealed attributes: firstName="YUSUF", lastName="ONCEL", dob="19810810", idDocType="2", idDocNo="G13618334", idDocIssuer="TR"

I have reached the identity information of the person belonging to the account.

**Comment by concordium-admin** [comment]
Hi donadel01

It's an interesting test case you tried out there. But what you can see is information, which is public by design of the blockchain and cannot be exploited maliciously.

1) Yes, it looks as if you can add an account belonging to someone else. However note that you cannot add the account specific secret key to decrypt nor the signing key to sign transactions. Hence, if you created a transaction from the account, you would need to sign it with a key you don't have. You can try another signing key but the bakers would eventually reject it when check the validity of the signature belonging to that specific account..

2) The identity information you can see on the chain are the attributes revealed by the user himself when creating an account. The balance is not the total balance but the general balance (i.e. unshielded), which is public by design as well. Note that the blockchain also provides the concept of a shielded balance, which cannot be read out by another user (who does not have the secret decryption key, see 1) ).

Hope this explanation could shed some light.
