### ISSUE TITLE
An error occurred when export account

### ISSUE THREAD

**Issue by ChauHuynh17071994** [Concordium/Testnet3-Challenges#1781]
installed the app on ios14.0.1
Create new account
select more and select export
select continue
Then error dialog show like in the picture. 
![possiblebug](https://user-images.githubusercontent.com/26538321/104846794-00da6580-58e5-11eb-88c2-c4485a403b50.jpg)

If it is not able to repeat the issues. Then can try to create one or two more new accounts and then select export

**Comment by concordium-cl** [comment]
Hi ChauHuynh17071994! 

You have reported this issue in the challenge repository for testnet3. Please note that Testnet3 was taken down when Testnet4 came up. Testnet4 and all related releases have it's own repository [here](https://github.com/Concordium/Testnet4-Challenges).

I will close this issue here, as I cannot see which version of mobile app and testnet you are referring to. Please create a new issue in the correct repository, if you feel it is an issue on testnet4 and the newest iOS release 0.1.63.

Thanks :blush: :+1:
