### ISSUE TITLE
some suggestion on send page

### ISSUE THREAD

**Issue by ChauHuynh17071994** [Concordium/Testnet3-Challenges#1782]
in the sending page currently, it not showing any balance for users to see. Also it good to have the option to send all or send max what users have in their wallets.

![suggestion](https://user-images.githubusercontent.com/26538321/104847011-5e22e680-58e6-11eb-89cb-c919b753cf06.jpg)

**Comment by ChauHuynh17071994** [comment]
Additionally, I see that the user can send 0 and still have to pay the fee. I know this is a functionality. But could we want users that they are sending 0 and they will have to pay the gas anyhow?

**Comment by concordium-cl** [comment]
Hi ChauHuynh17071994! 

You have reported this issue in the challenge repository for testnet3. Please note that Testnet3 was taken down when Testnet4 came up. Testnet4 and all related releases have it's own repository [here](https://github.com/Concordium/Testnet4-Challenges).

I will close this issue here, as I cannot see which version of mobile app and testnet you are referring to. Please create a new issue in the correct repository, if you feel it is an issue on testnet4 and the newest iOS release 0.1.63.

Thanks :blush: :+1:
