### ISSUE TITLE
Remove or delete or log out from account should be added 

### ISSUE THREAD

**Issue by ChauHuynh17071994** [Concordium/Testnet3-Challenges#1783]
Currently, there is no way to remove or delete an account. Should this be considered to add?

**Comment by concordium-cl** [comment]
Hi ChauHuynh17071994! 

You have reported this issue in the challenge repository for testnet3. Please note that Testnet3 was taken down when Testnet4 came up. Testnet4 and all related releases have it's own repository [here](https://github.com/Concordium/Testnet4-Challenges).

I will close this issue here, as I cannot see which version of mobile app and testnet you are referring to. Please create a new issue in the correct repository, if you feel it is an issue on testnet4 and the newest iOS release 0.1.63.

Thanks :blush: :+1:
