### ISSUE TITLE
Pull request for each task

### ISSUE THREAD

**Issue by bertco** [Concordium/Testnet3-Challenges#364]
https://github.com/Concordium/Testnet3-Challenges/issues/323
Is not explains the main question, we understood that each task has have different pull request - this is clear.

But by using this video https://youtu.be/VFGayA6ikU4  we have the technical limitations to make different pull request to each task if we will have the one branch. May be we have to choose "Create the new branch for this commit" instead of "Commit directly to the main branch" in the video?

**Comment by OykuMelikoglu** [comment]
Bertco is right, since we are using only the main branch. After we do the pull request with the main branch, we can no longer do another pull request but we are only able to edit the request. If you need us to make one pull request per challenge, we need to create and use other branches.
Also before I saw #323, because of the selection of main branch, my signed commits were directly added to the initial pull request. From now on, I can create a new branch every time for the new challenges, however the prior ones will be all together. All of those challenge submissions that I commited will be judged by the time stamp of the last one I submitted, am I correct? I do not need to commit and pull them again separately?

**Comment by supermario** [comment]
Sorry about the confusion here. Please create all PRs in the way you did the first – so always from a branch on your fork. This will allow you to set all the files properly. This will probably mean you need different branches for each PR, so just use something sensible like the Challenge ID, i.e. B1, B2, ID1, etc as the branch name.

I'll update the docs to this effect. If you already have comment-based or combined-PR based submissions before this message, we'll accept it as is.

**Comment by shortingbanks** [comment]
> #323
> Is not explains the main question, we understood that each task has have different pull request - this is clear.
> 
> But by using this video https://youtu.be/VFGayA6ikU4 we have the technical limitations to make different pull request to each task if we will have the one branch. May be we have to choose "Create the new branch for this commit" instead of "Commit directly to the main branch" in the video?

As @supermario suggested please use "Create new branch for this commit" instead of what was shown in the video

**Comment by senevrensel** [comment]
Why does that issue become so confusing.
Which challenge you wanna  go for submission  ?
1-Click the mission link 
2-Click fork
3-Click "Add file " on the top right 
4-Click Pull request.
That is all.

**Comment by eserow** [comment]
b2-b3b-b4 nasıl yapacagız
