### ISSUE TITLE
abrupt stop of chain synchronization

### ISSUE THREAD

**Issue by pablozsc** [Concordium/Testnet3-Challenges#849]
My node was up and running within 7 days and everything went smoothly. But today, when I went to the dashboard, I noticed that the last finalization was completed 20 hours ago. In this case, the uptime field showed that the node was online.
After I noticed this, I walked to the node, stopped it and started it again without rebuilding the chain. After rebooting, the node works fine, but the number of received and sent blocks has been reset.
I am attaching the logs of the first 1000 lines and the last. The logs were made before the node was rebooted.

node id ca2459aabfc8b7ef
head logs https://pastebin.com/A2PJaNyu
tail logs https://pastebin.com/URFw9VeK

**Comment by pablozsc** [comment]
![unknown](https://user-images.githubusercontent.com/72607589/96859094-c4c07180-1469-11eb-8ae3-e160fb840d9b.png)

**Comment by pablozsc** [comment]
I also noticed that some other nodes have a similar problem.
![Annotation 2020-10-22 150826](https://user-images.githubusercontent.com/72607589/96869925-d52c1880-1478-11eb-95bf-9ef4a8b9735b.png)
![Annotation 2020-10-22 150943](https://user-images.githubusercontent.com/72607589/96869928-d65d4580-1478-11eb-824d-3863f01da8a4.png)

**Comment by concordium-admin** [comment]
Hi paplozsc! 

Your node should of course not fall behind catching up with the chain. Is your node running on Linux/Windows/Mac?

Note that the number of received and sent messages is not persisted after a restart, so that part is as expected.

**Comment by pablozsc** [comment]
[concordium-testnet-system-report.log](https://github.com/Concordium/Testnet3-Challenges/files/5423287/concordium-testnet-system-report.log)

**Comment by pablozsc** [comment]
node based on cloud vps

**Comment by ab-concordium** [comment]
Unfortunately the logs you posted do not indicate enough information. Is there a chance you could provide us with full logs. If you did not reset data then the logs from the previous run should be there.

Do you have logs of the resource usage (specifically memory) of your node?

**Comment by pablozsc** [comment]
Unfortunately i don't have logs of resource usage.
But i got full logs of node, here:
https://drive.google.com/file/d/1RPiNCBwLOEDhQuAp5pSYAKUSht8XKRJ0/view?usp=sharing

**Comment by ab-concordium** [comment]
The logs only contain data until October 20 and end abruptly without any indication of what is wrong.

- Did you reset your node, i.e., did you run `reset-data`? If not, then the logs should still be there from the previous run.
- What time zone are the times in the two graphs you've posted (which I'm guessing are CPU usage and network usage?)

The tool for retrieving logs is a bit memory hungry, but you can just do it directly by running `docker logs`.
First, if you have the node running run `docker container list`. That should give you the `CONTAINER ID`.
Then use `docker logs $CONTAINER_ID` where $CONTAINER_ID is what you obtained in the previous step.
To reduce the amount of logs, just use to get the missing logs
`docker logs $CONTAINER_ID --since "2020-10-20T19:07:10"`

**Comment by pablozsc** [comment]
1. I did not reset my node. I just stop them (ctrl+c) and run again 
2. My timezone is moscow +3 UTC

here are logs with "docker logs $CONTAINER_ID --since "2020-10-20T19:07:10""
https://drive.google.com/file/d/1hbVmJZpRQSwlNEXOFWDUaS28ZaOsrcjv/view?usp=sharing

**Comment by ab-concordium** [comment]
Thank you for the logs.

Unfortunately they do not reveal the cause of the problem. It is clear that the node stopped sending and receiving messages around 2020-10-21 12:38:02 UTC time, but there is no indication on why, and then I see you restarted it the next morning.

There are no errors in the logs that would explain the root cause, so unfortunately there is not much I can do at this time.

**Comment by pablozsc** [comment]
Ok, then close this request.
But as I wrote above, some other nodes on the network faced the same problem. We can observe them right now in the dashboard. You can see the field "Last fin":
1. Node name moze | Node ID 635dab49790a6289
2. Node name pawleo | Node ID 311ee5063d491070
3. Node name catgromon | Node ID dcdcd343b93d0a5e
4. Node name mousey | Node ID a02a534b348c02c8
5. Node name Projecttent | Node ID cc88ea7fe63dc2e3
6. Node name please send GTU | Node ID a49eed604416d002
